[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
#solana_nft_anchor = "CqRWok13RhCNvBHGub1o8wUbpP2JvhWDQ1E9YcafC71N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
